// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, handlebars;

  express = require('express');

  app = express();

  handlebars = require('express3-handlebars').create({
    defaultLayout: 'main'
  });

  app.engine('handlebars', handlebars.engine);

  app.set('views engine', 'handlebars');

  app.use(express["static"](__dirname + '/public'));

  app.set('port', process.env.PROT || 3000);

  app.get('/', function(req, res) {
    return res.render('home');
  });

  app.get('/about', function(req, res) {
    var fortunes;
    fortunes = ["Conquer your fears or they will conquer you.", "Rivers need springs.", "Do not fear what you don't know.", "You will have a pleasant surprise.", "Whenever possible, keep it simple."];
    return res.render('about', {
      fortune: fortunes
    });
  });

  app.use(function(req, res) {
    return res.render('404');
  });

  app.use(function(err, req, res, next) {
    console.error(err.stack);
    return res.render('500');
  });

  app.listen(app.get('port'), function() {
    return console.log('Express started on http://localhost:' + app.get('port') + '; press Ctrl-C to terminate.');
  });

}).call(this);

//# sourceMappingURL=meadowlark.js.map
