// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, handlebars;

  express = require('express');

  app = express();

  handlebars = require('express3-handlebars').create({
    defaultLayout: 'main'
  });

  app.engine('handlebars', handlebars.engine);

  app.set('views engine', 'handlebars');

  app.set('port', process.env.PROT || 3000);

  app.get('/', function(req, res) {
    res.type('text/plain');
    return res.send('Meadowlark Travel');
  });

  app.get('/about', function(req, res) {
    res.type('text/plain');
    return res.send('About Meadowlark Travel');
  });

  app.use(function(req, res) {
    res.type('text/plain');
    res.status(404);
    return res.send('404 - Not Found');
  });

  app.use(function(err, req, res, next) {
    console.error(err.stack);
    res.type('text/plain');
    res.status(500);
    return res.send('500 - Server Error');
  });

  app.listen(app.get('port'), function() {
    return console.log('Express started on http://localhost:' + app.get('port') + '; press Ctrl-C to terminate.');
  });

}).call(this);

//# sourceMappingURL=meadowlark.js.map
